apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - https://github.com/redhat-appstudio/application-service/config/default?ref=9d879ead7c6096477d9aae864fa9371f0518ed13
components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/karthik_jk/application-service
    newTag: v0.0.1
configMapGenerator:
  - literals:
      - GITHUB_ORG=HACbs-ui-org
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace
namespace: application-service
