---
apiVersion: v1
data:
  role_id: NDFmYTc4YjUtZjA2MC1kMzQ2LTVhNDEtODA3YzZjMjc3MzQz
  secret_id: Y2YyYzViYTAtNTYxZS0yZDE2LTFiOTktZTRmYzA0MGVmZGU2
kind: Secret
metadata:
  creationTimestamp: null
  name: vault-approle-spi-operator
---
apiVersion: v1
data:
  role_id: ZjUxYjg1YjgtMzliNS05ZGE2LWFmMjctODI3YzRmMDA3ODQ1
  secret_id: MzYyM2YwY2ItYmE5MC0yNGFlLTQ1YzAtNjc3MjE4YzhjY2Rj
kind: Secret
metadata:
  creationTimestamp: null
  name: vault-approle-spi-oauth
