# add a route with fixed name so you can hardcode it in the environment
# note, this may be an issue in the reachability for public servers with access to keycloak 
# and the jdoe account
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak-auth
spec: 
  path: /
  to:
    kind: Service
    name: env-boot-keycloak
    weight: 100
  port:
    targetPort: keycloak
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None