sharedSecret: test
serviceProviders:
  - type: GitHub
    clientId: 211512
    clientSecret: 48f60cb4624b35d5bb7e74e58a8cb95d6dc0e52b
baseUrl: https://spi-oauth-route-spi-system.apps.ci-ln-q4jl5it-72292.origin-ci-int-gce.dev.rhcloud.com
