---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: authorization-in-kcp
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - kcp-name: kcp-stable
          - list:
              elements:
                - service: appstudio
                - service: hacbs
  template:
    spec:
      source:
        repoURL: https://github.com/karthikjeeyar/infra-deployments.git
        targetRevision: preview-kcp-test
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-service
spec:
  generators:
    - list:
        elements:
          - kcp-name: kcp-stable
  template:
    spec:
      source:
        repoURL: https://github.com/karthikjeeyar/infra-deployments.git
        targetRevision: preview-kcp-test
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spi
spec:
  generators:
    - list:
        elements:
          - kcp-name: kcp-stable
  template:
    spec:
      source:
        repoURL: https://github.com/karthikjeeyar/infra-deployments.git
        targetRevision: preview-kcp-test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spi-vault
spec:
  source:
    repoURL: https://github.com/karthikjeeyar/infra-deployments.git
    targetRevision: preview-kcp-test
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-api
spec:
  generators:
    - list:
        elements:
          - kcp-name: kcp-stable
  template:
    spec:
      source:
        repoURL: https://github.com/karthikjeeyar/infra-deployments.git
        targetRevision: preview-kcp-test
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: enterprise-contract
spec:
  generators:
    - list:
        elements:
          - kcp-name: kcp-stable
  template:
    spec:
      source:
        repoURL: https://github.com/karthikjeeyar/infra-deployments.git
        targetRevision: preview-kcp-test
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: build-service
spec:
  generators:
    - list:
        elements:
          - kcp-name: kcp-stable
  template:
    spec:
      source:
        repoURL: https://github.com/karthikjeeyar/infra-deployments.git
        targetRevision: preview-kcp-test
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jvm-build-service
spec:
  generators:
    - list:
        elements:
          - kcp-name: kcp-stable
  template:
    spec:
      source:
        repoURL: https://github.com/karthikjeeyar/infra-deployments.git
        targetRevision: preview-kcp-test
