resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/release-service/config/default?ref=b34c7417c1024aed159ffc50699afc4992e3fd5f
  - .tekton/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/redhat-appstudio/release-service
    newTag: b34c7417c1024aed159ffc50699afc4992e3fd5f

namespace: release-service

patches:
  - ./manager_resources_patch.yaml
