resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=d0196195fe69a63166b9e42823823f9139d676c2
  - .tekton/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-appstudio/integration-service
    newTag: d0196195fe69a63166b9e42823823f9139d676c2

namespace: integration-service

patches:
  - ./manager_resources_patch.yaml
