resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
<<<<<<< HEAD
- https://github.com/redhat-appstudio/integration-service/config/default?ref=14a0355396cafcd3ee51c5385eb0094f8866979f
=======
- https://github.com/redhat-appstudio/integration-service/config/default?ref=7b54e0b6ed9a22c85d9fb2f582d346f28f23b304
>>>>>>> 917d182 (bump versions)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
<<<<<<< HEAD
  newTag: 14a0355396cafcd3ee51c5385eb0094f8866979f
=======
  newTag: 7b54e0b6ed9a22c85d9fb2f582d346f28f23b304
>>>>>>> 917d182 (bump versions)

namespace: integration-service

patches:
  - ./manager_resources_patch.yaml
